"use client";

import { Loader2 } from "lucide-react";
import { MaterialSymbol } from "@/components/ui/MaterialSymbol";

type SessionAnalysisModalProps = {
  open: boolean;
  onClose: () => void;
  loading: boolean;
  summary: string | null;
  error: string | null;
  title: string;
};

export function SessionAnalysisModal({
  open,
  onClose,
  loading,
  summary,
  error,
  title,
}: SessionAnalysisModalProps) {
  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-[80] flex items-center justify-center bg-black/45 p-4 backdrop-blur-[2px]"
      role="dialog"
      aria-modal="true"
      onClick={onClose}
    >
      <div
        className="w-full max-w-2xl rounded-2xl border border-outline-variant/60 bg-surface-container-lowest shadow-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between gap-3 border-b border-outline-variant/50 px-6 py-5">
          <div className="flex items-center gap-3">
            <div className="flex size-10 items-center justify-center rounded-xl bg-primary-container text-primary">
              <MaterialSymbol name="psychology" filled className="text-2xl" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-on-surface">AI Session Analysis</h2>
              <p className="text-[12px] text-on-surface-variant font-medium">{title}</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 text-on-surface-variant hover:bg-surface-container-high transition-colors"
            aria-label="Close"
          >
            <MaterialSymbol name="close" />
          </button>
        </div>

        <div className="max-h-[min(70vh,600px)] overflow-y-auto px-8 py-8">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <div className="relative flex h-16 w-16 items-center justify-center">
                <div className="absolute inset-0 animate-ping rounded-full bg-primary/20" />
                <Loader2 className="h-10 w-10 animate-spin text-primary" />
              </div>
              <p className="mt-6 text-[15px] font-bold text-on-surface">Vrika AI is reasoning over your session logs...</p>
              <p className="mt-1 text-[13px] text-on-surface-variant">This may take up to 30 seconds depending on the number of tools executed.</p>
            </div>
          ) : error ? (
            <div className="rounded-xl border border-error/20 bg-error/5 p-6">
              <div className="flex items-center gap-3 text-error">
                <MaterialSymbol name="error" filled />
                <p className="font-bold">Analysis failed</p>
              </div>
              <p className="mt-3 text-[14px] leading-relaxed text-on-surface-variant">{error}</p>
            </div>
          ) : summary ? (
            <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
              <h3 className="text-[11px] font-bold uppercase tracking-[0.15em] text-primary">Executive Summary</h3>
              <div className="mt-4 text-[15px] leading-[1.7] text-on-surface-variant font-medium whitespace-pre-wrap">
                {summary}
              </div>
              
              <div className="mt-8 flex items-center gap-2 rounded-xl bg-surface-container-low px-4 py-3 border border-outline-variant/30">
                <MaterialSymbol name="info" className="text-primary text-xl" filled />
                <p className="text-[12px] text-on-surface-variant leading-tight">
                  This summary is generated by the Vrika Intelligence Engine. Detailed findings have been persisted to the session record.
                </p>
              </div>
            </div>
          ) : (
            <p className="text-center text-on-surface-variant py-12">No summary generated.</p>
          )}
        </div>

        <div className="flex justify-end gap-2 border-t border-outline-variant/50 px-6 py-4 bg-surface-container-lowest">
          <button
            type="button"
            onClick={onClose}
            className="rounded-xl px-5 py-2.5 text-[14px] font-bold text-on-surface hover:bg-surface-container-high transition-colors"
          >
            {loading ? "Cancel" : "Close"}
          </button>
        </div>
      </div>
    </div>
  );
}
